"use client";

import { useState } from 'react'
import './globals.css'
import Navbar from './navbar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation';
import { SessionProvider } from 'next-auth/react'


const inter = Inter({ subsets: ['latin'] })

const disableNavbar = ['/login', '/register'];

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <div className="flex flex-col h-screen">
            {!disableNavbar.includes(pathname) && <Navbar></Navbar>}
            {children}
          </div>
        </SessionProvider>
        </body>
    </html>
  )
}
